import './globals.css'
import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import Sidebar from '@/components/sidebar'
import SupabaseProvider from '@/providers/SupabaseProviders'
import UserProvider from '@/providers/UserProvider'
import ModalProviders from '@/providers/ModalProvider'
import ToasterProvider from '@/providers/toasterprovider'

const font = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ToasterProvider/>
        <SupabaseProvider>
            <UserProvider>
              <ModalProviders/>
              <Sidebar>
              {children}
              </Sidebar>
            </UserProvider>
        </SupabaseProvider>
        </body>
    </html>
  )
}
